baseURL = "https://annouimo-blog.pages.dev"
languageCode = "zh-CN"
title = "Annouimo 的个人博客"
theme = "hugo-PaperMod"
defaultContentLanguage = "zh"
buildDrafts = false

[params]
  description = ""
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  math = true
  mainSections = ["posts"]

  [params.profileMode]
    enabled = true
    title = "Annouimo"
    subtitle = ""
    imageUrl = "images/avatar.jpg"

[[module.imports]]
  path = "github.com/KKKZOZ/hugo-admonitions"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "chronicle"
    name = "项目编年史"
    url = "/chronicle/"
    weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3
